# ~/.config/starship.toml

# Formato personalizado para el prompt
# Use custom format
format = '''
[>](bold green)
[](bold blue)$directory$rust$package
[>](bold red) '''

# M贸dulo de bater铆a
[battery]
full_symbol = ' '  # Cuando la bater铆a est谩 llena
charging_symbol = '★ '  # Cuando la bater铆a est谩 cargando
discharging_symbol = ' '  # Cuando la bater铆a se est谩 descargando
disabled = false  # Activa este m贸dulo

# M贸dulo de hora
[time]
format = '[ $time](bold blue)'  # Hora con emoji
use_12hr = true  # Usa el formato de 12 horas
disabled = false  # Activa este m贸dulo

# M贸dulo de Java (si tienes Java instalado)
[java]
format = 'v$version'  # Muestra la versi贸n de Java
disabled = false  # Activa este m贸dulo

# M贸dulo de nombre de usuario
[username]
format = " [$user]($style)"  # Emoji de robot junto al nombre de usuario
style = "bold red"  # Color rojo en negrita para el nombre de usuario
